---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.0
before_install: gem install bundler -v 2.0.1
script:
  - bundle exec rspec
  - bundle exec rubocop

after_success:
  - bundle exec codeclimate-test-reporter
